# Generated by Django 2.1.7 on 2019-02-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tube', '0003_notifications_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='clan',
        ),
        migrations.AddField(
            model_name='clan',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
